export const errors = [
  {
    error_type: {
      id: 20,
      group: "ERRO",
      title: "CÓDIGO SKU DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "B2",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 61,
      group: "ERRO",
      title: "CORRELAÇÃO ERRADA ENTRE CÓDIGO DE PRODUTO E SKU",
      description: "",
      severity: 4,
      collector: "IA",
    },
    coor: "A2",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 21,
      group: "FORA DO PADRÃO",
      title: "ALTURA FORA DO PADRÃO DA SACOLA",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "N2",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 15,
      group: "ERRO",
      title: "CÓDIGO EAN DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "G2",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 62,
      group: "FORA DO PADRÃO",
      title: "FORA DO PADRÃO DE CADASTRO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "J2",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 20,
      group: "ERRO",
      title: "CÓDIGO SKU DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "B3",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 28,
      group: "ORTOGRAFIA",
      title: "ESPAÇAMENTO EXCEDENTE",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "B2",
    sheet: "PROD",
  },
  {
    error_type: {
      id: 15,
      group: "ERRO",
      title: "CÓDIGO EAN DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "G3",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 20,
      group: "ERRO",
      title: "CÓDIGO SKU DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "B4",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 15,
      group: "ERRO",
      title: "CÓDIGO EAN DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "G4",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 20,
      group: "ERRO",
      title: "CÓDIGO SKU DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "B5",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 15,
      group: "ERRO",
      title: "CÓDIGO EAN DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "G5",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 20,
      group: "ERRO",
      title: "CÓDIGO SKU DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "B6",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 28,
      group: "ORTOGRAFIA",
      title: "ESPAÇAMENTO EXCEDENTE",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "C6",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 15,
      group: "ERRO",
      title: "CÓDIGO EAN DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "G6",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 20,
      group: "ERRO",
      title: "CÓDIGO SKU DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "B7",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 2,
      group: "FORA DO PADRÃO",
      title: "GÊNERO FORA DO PADRÃO - ABA PRODUTO",
      description: "",
      severity: 2,
      collector: "IA",
    },
    coor: "G5",
    sheet: "PROD",
  },
  {
    error_type: {
      id: 15,
      group: "ERRO",
      title: "CÓDIGO EAN DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "G7",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 20,
      group: "ERRO",
      title: "CÓDIGO SKU DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "B8",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 2,
      group: "FORA DO PADRÃO",
      title: "GÊNERO FORA DO PADRÃO - ABA PRODUTO",
      description: "",
      severity: 2,
      collector: "IA",
    },
    coor: "G5",
    sheet: "PROD",
  },
  {
    error_type: {
      id: 15,
      group: "ERRO",
      title: "CÓDIGO EAN DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "G8",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 20,
      group: "ERRO",
      title: "CÓDIGO SKU DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "B9",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 15,
      group: "ERRO",
      title: "CÓDIGO EAN DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "G9",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 20,
      group: "ERRO",
      title: "CÓDIGO SKU DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "B10",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 24,
      group: "FORA DO PADRÃO",
      title: "IVA FORA DO PADRÃO",
      description: "",
      severity: 2,
      collector: "IA",
    },
    coor: "M10",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 15,
      group: "ERRO",
      title: "CÓDIGO EAN DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "G10",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 20,
      group: "ERRO",
      title: "CÓDIGO SKU DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "B11",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 15,
      group: "ERRO",
      title: "CÓDIGO EAN DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "G11",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 20,
      group: "ERRO",
      title: "CÓDIGO SKU DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "B12",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 15,
      group: "ERRO",
      title: "CÓDIGO EAN DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "G12",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 20,
      group: "ERRO",
      title: "CÓDIGO SKU DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "B13",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 15,
      group: "ERRO",
      title: "CÓDIGO EAN DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "G13",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 20,
      group: "ERRO",
      title: "CÓDIGO SKU DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "B14",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 15,
      group: "ERRO",
      title: "CÓDIGO EAN DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "G14",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 20,
      group: "ERRO",
      title: "CÓDIGO SKU DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "B15",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 15,
      group: "ERRO",
      title: "CÓDIGO EAN DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "G15",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 20,
      group: "ERRO",
      title: "CÓDIGO SKU DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "B16",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 15,
      group: "ERRO",
      title: "CÓDIGO EAN DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "G16",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 20,
      group: "ERRO",
      title: "CÓDIGO SKU DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "B17",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 15,
      group: "ERRO",
      title: "CÓDIGO EAN DUPLICADO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "G17",
    sheet: "SKU",
  },
  {
    error_type: {
      id: 62,
      group: "FORA DO PADRÃO",
      title: "FORA DO PADRÃO DE CADASTRO",
      description: "",
      severity: 3,
      collector: "IA",
    },
    coor: "K17",
    sheet: "SKU",
  },
];
